"""The gap review: every source-audit finding on the goal and the milestones, decided by the human.

    source_audit.py decisions MISSION_DIR      -> (re)writes MISSION_DIR/DECISIONS.md
    draft.py MISSION_DIR verify                -> counts every undecided or stale row as BAD

Why (QFS, 2026-09-27): the source audit flagged Theorem 1.4 as indirect -- the paper's "and the
corresponding norms are comparable" was not stated -- and the goal as indirect on the kernel's
diagonal. Both findings were dismissed by the captain in a running log, and the hand-off
summarised items by verdict word, so neither reached the human; the first surfaced only because
dbenbenn happened to ask about Theorem 1.4. A fidelity trade-off is the human's call. So every
finding becomes a row here, the captain writes a proposal, only the human's answer goes on the
`decided:` line, and verify refuses the Draft until every row has one.

A row is made for each claim or hypothesis the VERDICT line names (MISSING, WEAKER, EXTRA), and one
for a DIRECTNESS other than `direct`, on the goal and on every milestone that has a source (a
`page`). A paper item with no coverage file gets a row too: its audit is missing. Each item's
header records a fingerprint of its coverage.md; when the audit is re-run and the file changes,
the item's decisions move to `previously:` and the rows reopen, since a decision answers one audit.

Row format (edit only the `proposed:` and `decided:` lines):

    ### C10
    - auditor: <the coverage.md line for this claim>
    - proposed: <captain's recommendation: fixed / carried by X / out of scope / dismissed, why>
    - decided: <human>, <date>: <disposition>     (empty until the human decides)
"""
import hashlib, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

HEAD = """# Gap review: source-audit findings to decide

Generated by `source_audit.py decisions` from `readbacks/*.coverage.md`. One row per finding on the
goal or a milestone. The captain fills `proposed:`; **only the human fills `decided:`**. `draft.py
verify` counts every row with an empty `decided:`, and every item whose audit changed since this
file was generated, as BAD. Re-run the generator after any re-audit: decisions carry over while
the audit is unchanged, and reopen when it changes.

"""


def _fp(path):
    return hashlib.sha256(open(path, 'rb').read()).hexdigest()[:12] if os.path.exists(path) else 'none'


def _items(mdir):
    """[(key, coverage path, has_source)] for the goal and every milestone, in item order."""
    import draft
    M = draft.load(mdir)
    items, miles, order, _ = draft.desired(M, mdir)
    keys = [k for k in order if k in miles or k == M.GOAL]
    out, n = [], 0
    for k in keys:
        if k.startswith('ref:'):
            name = k[4:]
            R = [R for R in M.REFERENCES if R['theorem_name'] == name][0]
            has_src = bool(R.get('page'))
            title = R.get('milestone_title') or R.get('title') or name
        else:
            name = k
            T = [T for T in M.THEOREMS if T['name'] == k][0]
            has_src = T.get('page') is not None
            title = T.get('milestone_title') or T.get('title') or name
        # the human reviews on the platform, where milestones are M1, M2, ... in item order and
        # the goal has no number; a Lean name alone does not say which one (dbenbenn, 2026-09-29)
        if k in miles and k != M.GOAL:
            n += 1
            label = 'M%d — %s' % (n, title)
        else:
            label = 'Goal — %s' % title
        out.append((k, os.path.join(mdir, 'readbacks', name + '.coverage.md'), has_src, label))
    return out


def _findings(cov):
    """[(row id, auditor text)] from one coverage.md."""
    txt = open(cov, encoding='utf-8').read()
    rows = []
    v = re.search(r'^VERDICT:\s*(.+)$', txt, re.M)
    verdict = v.group(1).strip() if v else '(no VERDICT line)'
    if not verdict.lower().startswith('faithful'):
        ids = []
        # IDs outside parentheses only: the auditor's asides name faithful claims too
        # ("gaps: C1, C5 (... ball case C5a and alpha_0 clause C6 are faithful)", QFS Lemma A.1)
        bare = verdict
        while re.search(r'\([^()]*\)', bare):
            bare = re.sub(r'\([^()]*\)', '', bare)
        for i in re.findall(r'\b([CH]\d+[a-z]?)\b', bare):
            if i not in ids:
                ids.append(i)
        lines = txt.split('\n')
        for i in ids:
            line = None
            for n, l in enumerate(lines):
                # the claim's own bullet: its ID leads the line, or sits in the leading bold span
                # ("- **C3, C4, C5** MISSING", Monod) -- not a later mention in someone else's row
                b = re.match(r'^\s*[-*]\s*(?:\*\*([^*]+)\*\*|(\S+))', l)
                if b and i in re.findall(r'\b([CH]\d+[a-z]?)\b', b.group(1) or b.group(2) or ''):
                    # the whole bullet, not its first line: auditors wrap a bullet over several
                    # lines, and the human decides from this text ("The read-back uses C1 only in
                    # the single instance where the relation is the" -- cut off, Monod M6)
                    body = [l]
                    for c in lines[n + 1:]:
                        if not c.strip() or re.match(r'^\s*[-*]\s', c) or c.startswith('#'):
                            break
                        body.append(c)
                    line = ' '.join(' '.join(body).split()); break
            rows.append((i, line or '(named in VERDICT: %s)' % verdict))
        if not ids:
            rows.append(('VERDICT', verdict))
    d = re.search(r'^DIRECTNESS:\s*(.+)$', txt, re.M)
    if d and not d.group(1).strip().lower().startswith('direct'):
        # the whole paragraph: the line may wrap, and nothing here is truncated
        para = re.match(r'^DIRECTNESS:\s*(.+?)(?:\n\s*\n|\Z)', txt[d.start():], re.S)
        rows.append(('DIRECTNESS', ' '.join(para.group(1).split())))
    return rows


def _parse(path):
    """{(key, row): {'proposed':..., 'decided':..., 'previously':...}} and {key: fingerprint}."""
    rows, fps, key, rid = {}, {}, None, None
    if not os.path.exists(path):
        return rows, fps
    for l in open(path, encoding='utf-8'):
        m = re.match(r'^## (\S+) +— audit (\w+)', l)
        if m:
            key, rid = m.group(1), None
            fps[key] = m.group(2)
            continue
        m = re.match(r'^### (\S+)', l)
        if m and key:
            rid = m.group(1)
            rows[(key, rid)] = {'proposed': '', 'decided': '', 'previously': ''}
            continue
        m = re.match(r'^- (proposed|decided|previously):\s?(.*)$', l)
        if m and key and rid:
            rows[(key, rid)][m.group(1)] = m.group(2).strip()
    return rows, fps


def build(mdir):
    path = os.path.join(mdir, 'DECISIONS.md')
    old, old_fp = _parse(path)
    out, n_open, n_rows, clean = [HEAD], 0, 0, []
    for key, cov, has_src, label in _items(mdir):
        fp = _fp(cov)
        if not os.path.exists(cov):
            if not has_src:
                continue                    # beyond the paper: no source sentence to audit against
            finds = [('AUDIT', 'no source audit on record for this item (run source_audit.py)')]
        else:
            finds = _findings(cov)
        if not finds:
            clean.append(key)
            continue
        out.append('## %s — audit %s\n\n**%s**\n\n' % (key, fp, label))
        for rid, text in finds:
            prev = old.get((key, rid), {})
            same = old_fp.get(key) == fp
            decided = prev.get('decided', '') if same else ''
            previously = prev.get('previously', '') if same else (prev.get('decided') or prev.get('previously') or '')
            out.append('### %s\n- auditor: %s\n- proposed: %s\n- decided: %s\n' % (
                rid, text, prev.get('proposed', ''), decided))
            if previously:
                out.append('- previously: %s\n' % previously)
            out.append('\n')
            n_rows += 1
            n_open += not decided
    out.append('## Clean\n\nFaithful and direct, nothing to decide: %s\n' % (
        ', '.join('`%s`' % k for k in clean) or '(none)'))
    open(path, 'w', encoding='utf-8').write(''.join(out))
    print('wrote %s: %d finding(s), %d undecided; %d item(s) clean' % (path, n_rows, n_open, len(clean)))


def check(mdir):
    """[(key, why)] for verify: undecided rows, stale items, and a missing or out-of-date file."""
    path = os.path.join(mdir, 'DECISIONS.md')
    if not os.path.exists(path):
        return [('DECISIONS.md', 'missing: run source_audit.py decisions, then go over it with the human')]
    rows, fps = _parse(path)
    bad = []
    listed = set(fps)
    for key, cov, has_src, _label in _items(mdir):
        fp = _fp(cov)
        if key in fps and fps[key] != fp:
            bad.append((key, 'stale: its source audit changed after DECISIONS.md was generated; re-run decisions'))
        elif key not in listed and os.path.exists(cov) and _findings(cov):
            bad.append((key, 'has audit findings not in DECISIONS.md; re-run decisions'))
        elif key not in listed and not os.path.exists(cov) and has_src:
            bad.append((key, 'no source audit on record, and not in DECISIONS.md'))
    for (key, rid), r in rows.items():
        if not r['decided']:
            bad.append(('%s:%s' % (key, rid), 'gap-review finding not yet decided by the human'))
    return bad
